options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: bridgecrew/checkov
  args: ["-d", "."]

- name: hashicorp/terraform
  dir: environments/dev
  args: ["init", "-upgrade"]

- name: hashicorp/terraform
  dir: environments/dev
  args: ["plan", "-var-file=terraform.tfvars"]

- name: hashicorp/terraform
  dir: environments/dev
  args: ["apply", "-var-file=terraform.tfvars", "-auto-approve"]

- name: hashicorp/terraform
  dir: environments/test
  args: ["init", "-upgrade"]

- name: hashicorp/terraform
  dir: environments/test
  args: ["plan", "-var-file=terraform.tfvars"]

- name: hashicorp/terraform
  dir: environments/test
  args: ["apply", "-var-file=terraform.tfvars", "-auto-approve"]
